<a href="https://colab.research.google.com/github/priyankaVenkateshan/Machine-learning/blob/main/ML_CA_1_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CSC 530: MACHINE LEARNING

## CA-1 [E8122014] 

2. A hospital wants to develop a model to predict the severity of a patient's condition
upon admission. The hospital has data on patients' demographics, medical history,
and vital signs at admission. The hospital would like to use this information to
predict whether the patient's condition is mild, moderate, or severe.

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/patient_data.csv")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Age                         22 non-null     int64 
 1   Gender                      22 non-null     object
 2   Ethnicity                   22 non-null     object
 3   BMI                         22 non-null     int64 
 4   Blood Pressure (systolic)   22 non-null     int64 
 5   Blood Pressure (diastolic)  22 non-null     int64 
 6   Heart Rate                  22 non-null     int64 
 7   Respiratory Rate            22 non-null     int64 
 8   Oxygen Saturation Level     22 non-null     int64 
 9   Chronic Conditions          22 non-null     object
 10  Medications                 22 non-null     object
 11  Lab Test Results            22 non-null     object
 12  Chief Complaint             22 non-null     object
 13  Severity                    22 non-null     object
d

In [3]:
df.columns=df.columns.str.replace(' ','_')

In [4]:
df.columns

Index(['Age', 'Gender', 'Ethnicity', 'BMI', 'Blood_Pressure_(systolic)',
       'Blood_Pressure_(diastolic)', 'Heart_Rate', 'Respiratory_Rate',
       'Oxygen_Saturation_Level', 'Chronic_Conditions', 'Medications',
       'Lab_Test_Results', 'Chief_Complaint', 'Severity'],
      dtype='object')

In [5]:
df.describe()

Age        BMI  Blood_Pressure_(systolic)  \
count  22.000000  22.000000                  22.000000   
mean   48.272727  27.863636                 133.909091   
std    14.528074   3.870468                  14.857767   
min    27.000000  22.000000                 110.000000   
25%    36.250000  25.250000                 121.250000   
50%    46.500000  27.500000                 132.500000   
75%    58.000000  30.750000                 141.500000   
max    75.000000  35.000000                 170.000000   

       Blood_Pressure_(diastolic)  Heart_Rate  Respiratory_Rate  \
count                   22.000000   22.000000         22.000000   
mean                    88.181818   78.272727         16.909091   
std                      9.515083    6.048863          2.113654   
min                     72.000000   70.000000         14.000000   
25%                     80.000000   75.000000         16.000000   
50%                     87.500000   78.500000         16.000000   
75%                     94.750000   80.000000         18.000000   
max                    110.000000   90.000000         20.000000   

       Oxygen_Saturation_Level  
count                22.000000  
mean                 95.090909  
std                   2.505405  
min                  90.000000  
25%                  94.000000  
50%                  96.000000  
75%                  97.000000  
max                  98.000000

In [6]:
df1=df.select_dtypes(exclude=['object'])

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         22 non-null     int64
 1   BMI                         22 non-null     int64
 2   Blood_Pressure_(systolic)   22 non-null     int64
 3   Blood_Pressure_(diastolic)  22 non-null     int64
 4   Heart_Rate                  22 non-null     int64
 5   Respiratory_Rate            22 non-null     int64
 6   Oxygen_Saturation_Level     22 non-null     int64
dtypes: int64(7)
memory usage: 1.3 KB


In [8]:
# Import label encoder
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
df['Severity']= label_encoder.fit_transform(df['Severity'])
df['Severity'].unique()

array([2, 1, 0])

In [9]:
x=df1
y=df['Severity']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=11)

In [11]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC()

In [12]:
predit=model.predict(x_test)

In [13]:
from sklearn import metrics
metrics.mean_absolute_error(y_test,predit)

0.8

In [14]:
metrics.mean_squared_error(y_test,predit)

1.2

In [15]:
import numpy as np
rmse=np.sqrt(metrics.mean_squared_error(y_test,predit))
print(rmse)

1.0954451150103321


In [16]:
from sklearn.metrics import classification_report , confusion_matrix
print(classification_report(y_test,predit))
print(confusion_matrix(y_test,predit))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.33      1.00      0.50         1
           2       0.00      0.00      0.00         3

    accuracy                           0.40         5
   macro avg       0.28      0.67      0.39         5
weighted avg       0.17      0.40      0.23         5

[[1 0 0]
 [0 1 0]
 [1 2 0]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
#Scaling
from sklearn import preprocessing
df2=df1.copy()
#scaler=preprocessing.MinMaxScaler()->default feature_range=(0,1)
scalar=preprocessing.MinMaxScaler(feature_range=(0,1))
df2.iloc[:,:]=scalar.fit_transform(df2)

In [18]:
x=df2
y=df['Severity']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=5)

In [20]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC()

In [21]:
predit=model.predict(x_test)

In [22]:
from sklearn import metrics
metrics.mean_absolute_error(y_test,predit)

0.2

In [23]:
metrics.mean_squared_error(y_test,predit)

0.2

In [24]:
import numpy as np
rmse=np.sqrt(metrics.mean_squared_error(y_test,predit))
print(rmse)

0.4472135954999579


In [25]:
from sklearn.metrics import classification_report , confusion_matrix
print(classification_report(y_test,predit))
print(confusion_matrix(y_test,predit))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      0.50      0.67         2
           2       0.67      1.00      0.80         2

    accuracy                           0.80         5
   macro avg       0.89      0.83      0.82         5
weighted avg       0.87      0.80      0.79         5

[[1 0 0]
 [0 1 1]
 [0 0 2]]
